
# name: Unique project name (lowercase + underscores only)
# version: Project version (useful for packages and releases)
name: 'learn_dbt'
version: '1.0.0'

# Tells dbt which profile to use from profiles.yml
# The profile defines:
#  database type (Snowflake, BigQuery, Postgres, etc.)
#  credentials
#  target schema
profile: 'learn_dbt'

# SQL models (core of dbt)
model-paths: ["models"]
# Ad-hoc SQL (not built)
analysis-paths: ["analyses"]
# Generic & custom tests
test-paths: ["tests"]
# CSV files loaded as tables
seed-paths: ["seeds"]
# Jinja macros
macro-paths: ["macros"]
# Slowly changing dimension logic
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  learn_dbt:
    +materialized: view  # default for all models in the project
    staging:
      +materialized: ephemeral  # apply to child models
    marts:
      +materialized: table # apply to child models

vars:
  lookback_interval: '3 days'

seeds:
  learn_dbt:
    +quote_columns: false
